name: Build and Package
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install zip
          npm ci
        continue-on-error: true
      
      - name: Download joox-crypto with curl
        run: |
          curl -L https://git.unlock-music.dev/api/packages/um/npm/%40unlock-music%2Fjoox-crypto/-/0.0.1/joox-crypto-0.0.1.tgz -o joox-crypto-0.0.1.tgz
          npm install joox-crypto-0.0.1.tgz
        continue-on-error: true

      - name: Build
        run: |
          npm run build
          ls -R ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: latest-release
          
      - name: Build web
        run: |
          tar -czf legacy.tar.gz -C ./dist .
          (cd dist && zip -rJ9 ../legacy.zip *)

      - name: Make extension
        run: |
          npm run make-extension
          (cd dist && zip -rJ9 ../extension.zip *)

      - name: Build modern version
        run: |
          npm run build -- --modern
          tar -czf modern.tar.gz -C ./dist .
          (cd dist && zip -rJ9 ../modern.zip *)

      - name: Generate checksums
        run: sha256sum *.tar.gz *.zip > sha256sum.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            legacy.zip
            legacy.tar.gz
            extension.zip
            modern.zip
            modern.tar.gz
            sha256sum.txt


